spring.application.name=triagesystem

# DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/triage_db
spring.datasource.username=henrique
spring.datasource.password=password123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
app.jwt.secret=healthtech-triagesystem-super-secret-key-2024-must-be-at-least-256-bits
app.jwt.expiration-ms=86400000

# GEMINI AI (gratuito em aistudio.google.com)
gemini.api.key=${GEMINI_API_KEY}
gemini.model=gemini-2.0-flash-lite

# SPRINGDOC / SWAGGER
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# CORS (para desenvolvimento)
spring.web.cors.allowed-origins=*

# SERVER
server.port=8081
